<?php

// autoload_static.php @generated by Composer

namespace FavrEvents\Vendor\Composer\Autoload;

class ComposerStaticInitd25820c94c7efa8bf790125699b0dd6f
{
    public static $prefixLengthsPsr4 = array (
        'F' =>
        array (
            'FavrEvents\\Vendor\\FavrCore\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FavrEvents\\Vendor\\FavrCore\\' =>
        array (
            0 => __DIR__ . '/..' . '/favr/core/src',
        ),
    );

    public static $classMap = array (
        'FavrEvents\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FavrEvents\\Vendor\\FavrCore\\Admin\\FieldRenderer' => __DIR__ . '/..' . '/favr/core/src/Admin/FieldRenderer.php',
        'FavrEvents\\Vendor\\FavrCore\\Approvals\\Inbox' => __DIR__ . '/..' . '/favr/core/src/Approvals/Inbox.php',
        'FavrEvents\\Vendor\\FavrCore\\Fields\\FieldSet' => __DIR__ . '/..' . '/favr/core/src/Fields/FieldSet.php',
        'FavrEvents\\Vendor\\FavrCore\\Fields\\Sanitizer' => __DIR__ . '/..' . '/favr/core/src/Fields/Sanitizer.php',
        'FavrEvents\\Vendor\\FavrCore\\Integrations\\Elementor\\Widget' => __DIR__ . '/..' . '/favr/core/src/Integrations/Elementor/Widget.php',
        'FavrEvents\\Vendor\\FavrCore\\Moderation\\PendingChanges' => __DIR__ . '/..' . '/favr/core/src/Moderation/PendingChanges.php',
        'FavrEvents\\Vendor\\FavrCore\\Moderation\\Uploads' => __DIR__ . '/..' . '/favr/core/src/Moderation/Uploads.php',
        'FavrEvents\\Vendor\\FavrCore\\Support\\AssetVersion' => __DIR__ . '/..' . '/favr/core/src/Support/AssetVersion.php',
        'FavrEvents\\Vendor\\FavrCore\\Support\\CsvFormat' => __DIR__ . '/..' . '/favr/core/src/Support/CsvFormat.php',
        'FavrEvents\\Vendor\\FavrCore\\Support\\Hours' => __DIR__ . '/..' . '/favr/core/src/Support/Hours.php',
        'FavrEvents\\Vendor\\FavrCore\\Support\\RateLimit' => __DIR__ . '/..' . '/favr/core/src/Support/RateLimit.php',
        'FavrEvents\\Vendor\\FavrCore\\Support\\Template' => __DIR__ . '/..' . '/favr/core/src/Support/Template.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd25820c94c7efa8bf790125699b0dd6f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd25820c94c7efa8bf790125699b0dd6f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd25820c94c7efa8bf790125699b0dd6f::$classMap;

        }, null, ClassLoader::class);
    }
}
