<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitd25820c94c7efa8bf790125699b0dd6f
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('FavrEvents\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \FavrEvents\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitd25820c94c7efa8bf790125699b0dd6f', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \FavrEvents\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitd25820c94c7efa8bf790125699b0dd6f', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\FavrEvents\Vendor\Composer\Autoload\ComposerStaticInitd25820c94c7efa8bf790125699b0dd6f::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
